// Code generated by MockGen. DO NOT EDIT.
// Source: tokenRepository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entities "github.com/SemgaTeam/blog/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// GenerateAndSignToken mocks base method.
func (m *MockTokenRepository) GenerateAndSignToken(arg0 entities.Claims) (*entities.AuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAndSignToken", arg0)
	ret0, _ := ret[0].(*entities.AuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAndSignToken indicates an expected call of GenerateAndSignToken.
func (mr *MockTokenRepositoryMockRecorder) GenerateAndSignToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndSignToken", reflect.TypeOf((*MockTokenRepository)(nil).GenerateAndSignToken), arg0)
}
