// Code generated by MockGen. DO NOT EDIT.
// Source: hashRepository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHashRepository is a mock of HashRepository interface.
type MockHashRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHashRepositoryMockRecorder
}

// MockHashRepositoryMockRecorder is the mock recorder for MockHashRepository.
type MockHashRepositoryMockRecorder struct {
	mock *MockHashRepository
}

// NewMockHashRepository creates a new mock instance.
func NewMockHashRepository(ctrl *gomock.Controller) *MockHashRepository {
	mock := &MockHashRepository{ctrl: ctrl}
	mock.recorder = &MockHashRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashRepository) EXPECT() *MockHashRepositoryMockRecorder {
	return m.recorder
}

// HashPassword mocks base method.
func (m *MockHashRepository) HashPassword(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockHashRepositoryMockRecorder) HashPassword(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockHashRepository)(nil).HashPassword), arg0)
}

// IsPasswordValid mocks base method.
func (m *MockHashRepository) IsPasswordValid(arg0, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPasswordValid", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPasswordValid indicates an expected call of IsPasswordValid.
func (mr *MockHashRepositoryMockRecorder) IsPasswordValid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPasswordValid", reflect.TypeOf((*MockHashRepository)(nil).IsPasswordValid), arg0, arg1)
}
